platform :ios, '8.0'
use_frameworks!

workspace 'Actor'
xcodeproj 'Actor.xcodeproj'

inhibit_all_warnings!

target 'Actor' do
    xcodeproj 'Actor.xcodeproj'
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ActorSDK-iOS'
    pod 'Mixpanel'
    pod 'J2ObjC-Framework'
end